<?xml version="1.0" encoding="utf-8"?><Database Name="crudrg" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\crudrg.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="crudrgConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.MyData" Member="MyDatas">
    <Type Name="MyData">
      <Column Name="RollNumber" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="StudentName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FatherName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MotherName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>